### PR TITLE
extract stats from Home

### PR DESCRIPTION
**Pull request by MatiasOS**
This remove duplicated code, and increase readability.

### CODE REVIEW

**Comment by skkr** [comment]
@MatiasOS some comments: 

- We'll need to have a prop to set the color of the numbers _(via a css class `text-xxxx`)_ as in the previous version
- The link, to FAQs might be to a specific question in FAQs page
- We should be able to use different icons
- We can remove the `justify-self-center` class, is not really necessary
- I would recommend to keep the "column" classes as part of the view's layout and use only the "card" as a component _(maybe in a separated file?)_

**Comment by MatiasOS** [comment]
@skkr Done! 
Also I add a new Layout and container for the Stat components. And, part of #10, The stat container is making the call to etherScan.

**Comment by skkr** [comment]
@MatiasOS what I meant was to keep the layout "structure" in the homepage, and use the component only for the cards. but if you think there is an added value on having a separated file for the stats layout, we can keep it that way.

In that case, though, I think it should be treated ad a component and renamed to something like "StatsGroup", since its purpose is not to define a reusable scaffolding (a layout with interchangeable contents), but to display a set of stats together.

Also, two small details:
- We still need a prop to set the text color of the numbers. 
- The first icon should be "account_balance_wallet"

**Comment by skkr** [comment]
Perfect!

**Pull request merged**
